# Site settings
baseurl = "/"
themesDir = "themes"
languageCode = "en-us"
title = "Cybersecurity"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "Mihailo Kalinic"
	description = "Hugo Static Website"
	bio = "3rd year Computing Science Studio"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    linkedin = "https://au.linkedin.com/in/mihailo-kalinic-19b850171"
    github   = "https://www.github.com/MihailoKal"
